FROM gradle:9.0-jdk21

WORKDIR /app

# En mode dev, on ne fait PAS de COPY sélectif ni de RUN gradle dependencies.
# Pourquoi ? Parce qu'on va monter tout notre répertoire via le docker-compose.
# On copie juste le strict minimum pour que l'image soit valide.
COPY . .

EXPOSE 8080
EXPOSE 5005

# C'est ici, au moment du CMD, que le volume ~/.m2 sera là.
# Gradle trouvera alors tes dépendances locales.
CMD ["gradle", "bootRun", "--no-daemon", "-Pargs=-Dspring.profiles.active=integ"]